[package]
name = "RCHIP-8"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"
description = "chip-8 emulator written in rust"
repository = "https://github.com/Cheese-Space/RCHIP-8"
categories = ["emulators"]
authors = ["Cheese-Space"]
[dependencies]
rand = "0.10.0"
sdl3 = { version = "0.17.3", features = ["build-from-source-static"] }
serde_json = "1.0.149"
sha1_smol = "1.0.1"
